// Generated by CoffeeScript 1.6.3
(function() {
  _.mixin({
    inArray: function(arr, val) {
      return _.indexOf(arr, val) > -1;
    },
    quoteVal: function(val) {
      return _.template('"<%= val >"', {
        'val': 'val',
        val: val
      });
    }
  });

}).call(this);

/*
//@ sourceMappingURL=muckraking.map
*/
