// Generated by CoffeeScript 1.6.3
(function() {
  _.each($(wrapset), function(el) {
    var $containerEl, elHeight, elWidth, fitHeight, fitWidth, naturalSize;
    $containerEl = $(_.chain([containerEl, $(el).parent(), window]).compact().first().value());
    fitWidth = $containerEl.outerWidth();
    fitHeight = $containerEl.outerHeight();
    naturalSize = _.getNaturalSize(el);
    elWidth = naturalSize[0];
    elHeight = naturalSize[1];
    while (elWidth >= fitWidth && elHeight >= fitHeight) {
      elWidth--;
      elHeight--;
    }
    return $(el).attr({
      'width': elWidth + 1,
      'height': elHeight + 1
    }).css({
      'width': (elWidth + 1) + 'px',
      'height': (elHeight + 1) + 'px'
    }).addClass('resized');
  });

  if (!!_.isFunction(callback)) {
    callback(wrapset);
  }

}).call(this);

/*
//@ sourceMappingURL=muckraking.map
*/
